USE db_escola_M;

--IRÁ EXIBIR SOMENTE AS COLUNAS PAERSONALIZADAS(DIFERENTES DO *)
SELECT id, nome FROM tb_escola;

--SELECT TOP LIMITA A QUANTIDADE DE REGISTROS
SELECT TOP 3 nome FROM tb_aluno;

--EXEBIR SOMENTE 3 REGISTROS DO MAIS RECENTE PARA O MENOS RECENTE
SELECT TOP 3 nome 
FROM tb_aluno
ORDER BY id DESC;

--EXIBE SOMENTE O NOME DA TURMA DO PERIODO DA MANHÃ
SELECT * FROM tb_turma

SELECT nome_turma
FROM tb_turma
WHERE periodo = 'Manhã';

--EXIBE A PROVA DA PROFESSORA janaina
SELECT * FROM tb_prova
WHERE nome_professor = 'Fernanda';

--EXIBE QUANTOS ALUNOS TEM
SELECT COUNT(cpf) AS qtd_total_aluno FROM tb_aluno;


